/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LoanEmployee;

import Business.Enterprise.Enterprise;
import Business.Organization.LoanOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jagman
 */
public class LoanEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanEmployeeWorkAreaJPanel
     */
    private UserAccount account; 
    private LoanOrganization organization ;
    private Enterprise enterprise;
    private JPanel panel;
    public LoanEmployeeWorkAreaJPanel(JPanel panel ,  UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.account= account;
        this.organization = (LoanOrganization)organization ;
        this.enterprise = enterprise;
        value1.setText(enterprise.getName());
        value2.setText(account.getEmployee().getName());
        populateTable();  
       // populateProcessTable();
       DetailsPanel.setVisible(false);
    }
    
    
    @SuppressWarnings("empty-statement")
    private void populateTable() {
    
    DefaultTableModel model = (DefaultTableModel) loanjTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
             System.out.println("request" +request);
             
           BankRequest req=(BankRequest)request;
          
            Object[] row = new Object[6];
            row[0] = req.getRequestDate();
            row[1] = req.getBankName();
            row[2] = req.getFarmerName();
            row[3] = req.getStatus() == "Sent to the Bank" ? "Pending with Bank Loan Dept" : req.getStatus();
            row[4] = request;
            row[5] = req.getResolveDate();   
            model.addRow(row);
    
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanjTable = new javax.swing.JTable();
        assignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        value1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        value2 = new javax.swing.JLabel();
        showDetails = new javax.swing.JButton();
        DetailsPanel = new javax.swing.JPanel();
        acctNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loanAmont = new javax.swing.JTextField();
        loanReason = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hideButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        loanjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request Raised Date", "Bank Name", "Farmer Name", "Status", "Comments", "Resolved Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(loanjTable);

        assignButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        assignButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/assigntome.png"))); // NOI18N
        assignButton.setText("Assing To Me");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Loan Dept Work Area");

        value1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        value1.setText("<value>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Enterprise :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Employee :");

        value2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        value2.setText("<value>");

        showDetails.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        showDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-drug-to-prescription.png"))); // NOI18N
        showDetails.setText("Show Details ");
        showDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsActionPerformed(evt);
            }
        });

        DetailsPanel.setBackground(new java.awt.Color(153, 153, 255));
        DetailsPanel.setEnabled(false);

        acctNum.setEditable(false);
        acctNum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        acctNum.setEnabled(false);
        acctNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Account Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Loan Amount :");

        loanAmont.setEditable(false);
        loanAmont.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanAmont.setEnabled(false);
        loanAmont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmontActionPerformed(evt);
            }
        });

        loanReason.setEditable(false);
        loanReason.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanReason.setEnabled(false);
        loanReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanReasonActionPerformed(evt);
            }
        });

        loanTermTextField.setEditable(false);
        loanTermTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanTermTextField.setEnabled(false);
        loanTermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Loan Term:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Loan Reason :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Details ");

        hideButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        hideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-another-durg.png"))); // NOI18N
        hideButton.setText("Hide");
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 103, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        processButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        processButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/process.png"))); // NOI18N
        processButton.setText("Process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(value1)
                            .addComponent(value2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(assignButton)
                            .addGap(65, 65, 65)
                            .addComponent(showDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(value1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(value2))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(assignButton)
                        .addComponent(processButton)))
                .addGap(18, 18, 18)
                .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        int selectedRow = loanjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } else {

            WorkRequest request = (WorkRequest) loanjTable.getValueAt(selectedRow, 4);
            if (request.getReceiver() != null) {
                JOptionPane.showMessageDialog(null, "This request has alread been assigned");
            } else if((request.getStatus().equalsIgnoreCase("Approved") && (request.getResolveDate()==null)) || request.getStatus().equalsIgnoreCase("Intermidate") || request.getStatus().equalsIgnoreCase("Verified") || request.getStatus().equalsIgnoreCase("Rejected") ||request.getStatus().equalsIgnoreCase("Pending with loan approval")) {
            
            JOptionPane.showMessageDialog(null, "Cannot assign !! This request is ethier alrady approved or in intermidate state","info",JOptionPane.INFORMATION_MESSAGE);
            }else {
                request.setReceiver(account);
                request.setStatus("Pending with" +account.getEmployee().getName());
              //  populateProcessTable();
                populateTable();
            }

        }
    }//GEN-LAST:event_assignButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
         int selectedRow = loanjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } else {

            WorkRequest request = (WorkRequest) loanjTable.getValueAt(selectedRow, 4);
            
            
            
            if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Intermidate") ) {
            
            JOptionPane.showMessageDialog(null, "This request is already in other state","info",JOptionPane.INFORMATION_MESSAGE);
            }else if (request.getReceiver() !=null ){
                    if(request.getReceiver().equals(account)){
                request.setSender(account);
                request.setStatus("Intermidate") ;
                request.setReceiver(null);
               // populateProcessTable();
                populateTable();
            
                    }}else {
            
            JOptionPane.showMessageDialog(null, "Kindly assign the request first!!","info",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void acctNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumActionPerformed

    private void loanAmontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmontActionPerformed

    private void loanReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanReasonActionPerformed

    private void showDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsActionPerformed
        int selectedRow = loanjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } else {

            WorkRequest request = (WorkRequest) loanjTable.getValueAt(selectedRow, 4);
            BankRequest req=(BankRequest)request;
            DetailsPanel.setVisible(true);
            loanAmont.setText(Integer.toString(req.getLoanAmount()));
            acctNum.setText(req.getAccountNumber());
            loanReason.setText(req.getLoanReason());
            loanTermTextField.setText(Integer.toString(req.getLoanTerm()));
            
            
            
        }
    }//GEN-LAST:event_showDetailsActionPerformed

    private void loanTermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTermTextFieldActionPerformed

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        DetailsPanel.setVisible(false);
    }//GEN-LAST:event_hideButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JTextField acctNum;
    private javax.swing.JButton assignButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanAmont;
    private javax.swing.JTextField loanReason;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JTable loanjTable;
    private javax.swing.JButton processButton;
    private javax.swing.JButton showDetails;
    private javax.swing.JLabel value1;
    private javax.swing.JLabel value2;
    // End of variables declaration//GEN-END:variables
}
