/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BackgroundCheck;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BackgroundCheckOrganization;
import Business.Organization.LoanOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nidhi
 */
public class BackgroundCheckWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundCheckWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount account; 
    private Organization organization ;
    private Enterprise enterprise;
    
    public BackgroundCheckWorkAreaJPanel(JPanel container,UserAccount account,Organization organization,
            Enterprise enterprise) {
        initComponents();
        this.container=container;
        
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        entValue.setText(enterprise.getName());
        orgValue.setText(organization.getName());
        populateTable();
        DetailsPanel.setVisible(false);
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) backgroundCheckjTable.getModel();
        
        model.setRowCount(0);
        
         for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            BankRequest req =(BankRequest)request;
            Object[] row = new Object[5];
            row[0] = req.getRequestDate();
            row[1]=  req.getFarmerName();
            row[2] = req.getReceiver()==null ? "Not assigned" : req.getReceiver()  ;
            row[3] = req.getStatus();
            row[4] = request; 
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backgroundCheckjTable = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entValue = new javax.swing.JLabel();
        orgValue = new javax.swing.JLabel();
        DetailsPanel = new javax.swing.JPanel();
        acctNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loanAmont = new javax.swing.JTextField();
        loanReason = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hideButton = new javax.swing.JButton();
        showDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        backgroundCheckjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request raised date", "Farmer Name", "Reciever", "Status", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(backgroundCheckjTable);

        assignBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        assignBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/assigntome.png"))); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        processBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/process.png"))); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Enterprise:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Organisation: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Background Check Work Area");

        entValue.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        entValue.setText("<value>");

        orgValue.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        orgValue.setText("<value>");

        DetailsPanel.setBackground(new java.awt.Color(153, 153, 255));
        DetailsPanel.setEnabled(false);

        acctNum.setEditable(false);
        acctNum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        acctNum.setEnabled(false);
        acctNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Account Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Loan Amount :");

        loanAmont.setEditable(false);
        loanAmont.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanAmont.setEnabled(false);
        loanAmont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmontActionPerformed(evt);
            }
        });

        loanReason.setEditable(false);
        loanReason.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanReason.setEnabled(false);
        loanReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanReasonActionPerformed(evt);
            }
        });

        loanTermTextField.setEditable(false);
        loanTermTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanTermTextField.setEnabled(false);
        loanTermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Loan Term:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Loan Reason :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Details ");

        hideButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        hideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-another-durg.png"))); // NOI18N
        hideButton.setText("Hide");
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 103, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        showDetails.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        showDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-drug-to-prescription.png"))); // NOI18N
        showDetails.setText("Show Details ");
        showDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orgValue)
                            .addComponent(entValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(assignBtn)
                        .addGap(179, 179, 179)
                        .addComponent(showDetails)
                        .addGap(206, 206, 206)
                        .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entValue)
                        .addGap(18, 18, 18)
                        .addComponent(orgValue)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBtn)
                    .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        
       
         int selectedRow =backgroundCheckjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } 
        else{
            
            WorkRequest request = (WorkRequest) backgroundCheckjTable.getValueAt(selectedRow, 4);
            if (request.getReceiver() != null) {
                JOptionPane.showMessageDialog(null, "This request is already assigned");
            } else if((request.getStatus().equalsIgnoreCase("Approved") && (request.getResolveDate() !=null))||request.getStatus().equalsIgnoreCase("Verified") || request.getStatus().equalsIgnoreCase("Rejected") ||request.getStatus().equalsIgnoreCase("Pending with loan approval") ) {
            
            JOptionPane.showMessageDialog(null, "This request is already completed","info",JOptionPane.INFORMATION_MESSAGE);
            }else if(request.getStatus().equalsIgnoreCase("Sent to the Bank") || request.getStatus().equalsIgnoreCase("Pending with Bank Loan Dept")){
              JOptionPane.showMessageDialog(null, "This request is with the Loan Dept. Wait till it is prcoessed from that department","info",JOptionPane.INFORMATION_MESSAGE);
            }else {
            request.setReceiver(account);
            populateTable();
        } }
            

        
    }//GEN-LAST:event_assignBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = backgroundCheckjTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        }
        
        WorkRequest request = (WorkRequest)backgroundCheckjTable.getValueAt(selectedRow, 4);
       
        if(request.getReceiver() == account){
        request.setStatus("Processing with" +account.getEmployee().getName());
        
        BackgroundProcessJPanel background = new BackgroundProcessJPanel(container, request,account);
        container.add("BackgroundProcessJPanel", background);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        }else {
        
        JOptionPane.showMessageDialog(null, "This request is not assigned to you !!!" ,"warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_processBtnActionPerformed

    private void acctNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumActionPerformed

    private void loanAmontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmontActionPerformed

    private void loanReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanReasonActionPerformed

    private void loanTermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTermTextFieldActionPerformed

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        DetailsPanel.setVisible(false);
    }//GEN-LAST:event_hideButtonActionPerformed

    private void showDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsActionPerformed
        int selectedRow = backgroundCheckjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } else {

            WorkRequest request = (WorkRequest) backgroundCheckjTable.getValueAt(selectedRow, 4);
            BankRequest req=(BankRequest)request;
            DetailsPanel.setVisible(true);
            loanAmont.setText(Integer.toString(req.getLoanAmount()));
            acctNum.setText(req.getAccountNumber());
            loanReason.setText(req.getLoanReason());
            loanTermTextField.setText(Integer.toString(req.getLoanTerm()));

        }
    }//GEN-LAST:event_showDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JTextField acctNum;
    private javax.swing.JButton assignBtn;
    private javax.swing.JTable backgroundCheckjTable;
    private javax.swing.JLabel entValue;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanAmont;
    private javax.swing.JTextField loanReason;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JLabel orgValue;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton showDetails;
    // End of variables declaration//GEN-END:variables
}
