/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankManager;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Nidhi
 */
public class BankManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankManagerJPanel
     */
    private Enterprise enterprise;
    private UserAccount account;
   
    double i;
    double a;
    double b;
    double c;
        
    double perA;
    double perI;
    double perS;
    
    int app;
    int diss;
   // int total;
    //double appRate;
    //double dissRate;
    public BankManagerJPanel(JPanel panel ,UserAccount account,Organization organization,
        Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        entValue.setText(enterprise.getName());
        
      
        
        i=a=b=c=perA=perI=perS=0;
        //total=app=diss=0;
    }
    
     public void pieChart(){
        
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
        BankRequest req=(BankRequest)request;
                        
                    if (req.getLoanReason().equalsIgnoreCase("Agriculture Land")){
                         a+=1;
                    }
                 else if(req.getLoanReason().equalsIgnoreCase("Irrigation")){
                         b+=1;
                    }
                 else if(req.getLoanReason().equalsIgnoreCase("Seeds and fertilizers")){
                         c+=1;
                    }
                   }
                    i = a+b+c;
                        
                     perA = (a/i)*100;
                     perI = (b/i)*100;
                     perS = (c/i)*100;

                     System.out.println("Percentage of agricultral loan: "+perA);
                     System.out.println("Percentage of Irrigation loan: "+perI);
                     System.out.println("Percentage of Fertilizer loan: "+perS);
                     
                     DefaultPieDataset pieDataSet = new DefaultPieDataset();
        
                     pieDataSet.setValue("Agricultural based loan", +perA);
                     pieDataSet.setValue("Irrigation based loan", +perI);
                     pieDataSet.setValue("Seeds & Fertilizers based loan", +perS);
                     
                     JFreeChart chart = ChartFactory.createPieChart3D("Status", pieDataSet, true, true, true);
                     PiePlot3D p = (PiePlot3D)chart.getPlot();
                     ChartFrame frame = new ChartFrame ("Status", chart);
                     frame.setVisible(true);
                     frame.setSize(500,650);

    }
     
     public void ApprovalRate(){
         
         for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
        
        if (request.getStatus().equalsIgnoreCase("Approved")) {
            app+=1;
        }
        
        else if (request.getStatus().equalsIgnoreCase("Rejected")){
            diss+=1;
        }
        else if (request.getStatus().equalsIgnoreCase("Dissapproved")){
            diss+=1;
        }
        
         }
        
        //total=app+diss;
        //appRate= (app/total)*100;
        //dissRate=(diss/total)*100;
        System.out.println("Approvals: "+app);
        System.out.println("Disspprovals: "+diss);
        //System.out.println("Approval rate: "+appRate);
        
        
        DefaultPieDataset approval = new DefaultPieDataset();
        
                     approval.setValue("Approval rate", +app);
                     approval.setValue("Disspproval rate", +diss);

        
        
                     JFreeChart chart = ChartFactory.createPieChart("Status", approval, true, true, true);
                     PiePlot p = (PiePlot)chart.getPlot();
                     ChartFrame frame = new ChartFrame ("Approval/Dissaproval Rate", chart);
                     frame.setVisible(true);
                     frame.setSize(500,650);
     }                                     


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entValue = new javax.swing.JLabel();
        loanAnalysisBtn = new javax.swing.JButton();
        appRateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("  Bank Manager ");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Enterprise:");

        entValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        entValue.setText("<value>");

        loanAnalysisBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanAnalysisBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/generate-Graph.png"))); // NOI18N
        loanAnalysisBtn.setText("Loan Analysis");
        loanAnalysisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAnalysisBtnActionPerformed(evt);
            }
        });

        appRateBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        appRateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Pie-Chart-icon.png"))); // NOI18N
        appRateBtn.setText("Approval rate");
        appRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appRateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74)
                        .addComponent(entValue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appRateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loanAnalysisBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entValue))
                .addGap(47, 47, 47)
                .addComponent(loanAnalysisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appRateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loanAnalysisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAnalysisBtnActionPerformed
        // TODO add your handling code here:
        pieChart();
    }//GEN-LAST:event_loanAnalysisBtnActionPerformed

    private void appRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appRateBtnActionPerformed
        // TODO add your handling code here:
        ApprovalRate();
    }//GEN-LAST:event_appRateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appRateBtn;
    private javax.swing.JLabel entValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loanAnalysisBtn;
    // End of variables declaration//GEN-END:variables
}
