/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Farmers.Farmer;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jagman
 */
public class FarmerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerWorkAreaJPanel
     */
    private JPanel container;
    private EcoSystem system; 
    private UserAccount account; 
    Enterprise enterprise ;
    public FarmerWorkAreaJPanel(JPanel panel , EcoSystem system,UserAccount account ) {
        initComponents();
        this.container=panel;
        this.system = system;
        this.account= account; 
        createTabs(account);
    }
    
    public void createTabs(UserAccount account) {
        LoanStatusJPanel loanStatus=new LoanStatusJPanel(account);
        tabbedPane.add("Loan Status",loanStatus);
        SuppliesStatusJPanel supply=new SuppliesStatusJPanel(account);
        tabbedPane.add("Supplies Status",supply);
        InformationJPanel info =new InformationJPanel(container);
        tabbedPane.add("Informationn Channel",info);
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loanapplyJButton = new javax.swing.JButton();
        orderSuppliesJButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Farmers Work Area");

        loanapplyJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanapplyJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/create-account-Metro-icon.png"))); // NOI18N
        loanapplyJButton.setText("Apply For Loan");
        loanapplyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanapplyJButtonActionPerformed(evt);
            }
        });

        orderSuppliesJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderSuppliesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/recp-cart-add.png"))); // NOI18N
        orderSuppliesJButton.setText("Order Supplies");
        orderSuppliesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSuppliesJButtonActionPerformed(evt);
            }
        });

        tabbedPane.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(loanapplyJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(orderSuppliesJButton)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanapplyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderSuppliesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderSuppliesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSuppliesJButtonActionPerformed
        CardLayout layout = (CardLayout)container.getLayout();
//        for(Network network:system.getNetworkList()){
//                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
//                    if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Supplier")){
//                        this.enterprise = enterprise;
//                        break;
//                    }
//                }}
        container.add("RequestSuppliesJPanel", new OrderSupplies(container, system ,account,null ));
        layout.next(container);
    }//GEN-LAST:event_orderSuppliesJButtonActionPerformed

    private void loanapplyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanapplyJButtonActionPerformed
        CardLayout layout = (CardLayout)container.getLayout();
        if(system.getNetworkList()!= null) {
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Bank")){
                        this.enterprise = enterprise;
                        break;
                    }
                }}
        container.add("RequestLoanJPanel", new LoanApplicationJPanel(container, system,account,null ));
        layout.next(container); }
    }//GEN-LAST:event_loanapplyJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loanapplyJButton;
    private javax.swing.JButton orderSuppliesJButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
