/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.FarmerRole;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
/**
 *
 * @author Jagman
 */
public class InformationJPanel extends javax.swing.JPanel {

    /** Creates new form InformationJPanel */
    private JPanel container ; 
    public InformationJPanel(JPanel container ) {
        initComponents();
        this.container=container;
    }

    
    
     public void viewVideo(String url){
         
       final  Browser browser = new Browser();
       BrowserView browserView = new BrowserView(browser);
       JFrame frame = new JFrame();
       frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
       frame.add(browserView, BorderLayout.CENTER);
       frame.setSize(900, 500);
       frame.setLocationRelativeTo(null);
       frame.setVisible(true);
       browser.loadURL(url);
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agriBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wondersBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ecoBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        trimbleBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ecoBtn1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Educate Yourself");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html> <body> <p><b> 2)Wonders of Agriculture</b></p> <p></p> <p>Agriculture related videos from all over the world.</p> </body> </html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        agriBtn.setBackground(new java.awt.Color(0, 0, 0));
        agriBtn.setForeground(new java.awt.Color(255, 255, 255));
        agriBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Other-Search-Metro-icon.png"))); // NOI18N
        agriBtn.setText("View");
        agriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agriBtnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html> <body> <p><b> 3) Advancing Eco Agriculture</b></p> <p></p> <p>Create regenerative agricultural systems that help farmers growing disease and insect resistant crops with complete nutrition. </p> </body> </html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        wondersBtn.setBackground(new java.awt.Color(0, 0, 0));
        wondersBtn.setForeground(new java.awt.Color(255, 255, 255));
        wondersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Other-Search-Metro-icon.png"))); // NOI18N
        wondersBtn.setText("View");
        wondersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wondersBtnActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html> <body> <p><b> 1) What is Agriculture?</b></p> <p></p> <p>Watch the video to know about Agriculture.</p> </body> </html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ecoBtn.setBackground(new java.awt.Color(0, 0, 0));
        ecoBtn.setForeground(new java.awt.Color(255, 255, 255));
        ecoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Other-Search-Metro-icon.png"))); // NOI18N
        ecoBtn.setText("View");
        ecoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecoBtnActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html> <body> <p><b> 4)Trimble Agriculture</b></p> <p></p> <p>Solutions that can meet most any farmer's need regardless of farm size or brand of machinery. Trimble Agriculture solutions allow farmers to operate more efficiently and productively, save on input costs.</p> </body> </html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        trimbleBtn.setBackground(new java.awt.Color(0, 0, 0));
        trimbleBtn.setForeground(new java.awt.Color(255, 255, 255));
        trimbleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Other-Search-Metro-icon.png"))); // NOI18N
        trimbleBtn.setText("View");
        trimbleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trimbleBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("<html> <body> <p><b> 5)Most useful machines:</b></p> <p></p> <p>Wonderful Farming Equipment.</p> </body> </html>");

        ecoBtn1.setBackground(new java.awt.Color(0, 0, 0));
        ecoBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ecoBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Other-Search-Metro-icon.png"))); // NOI18N
        ecoBtn1.setText("View");
        ecoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecoBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wondersBtn)
                                    .addComponent(ecoBtn1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agriBtn)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ecoBtn)
                            .addComponent(trimbleBtn))))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trimbleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wondersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ecoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(481, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agriBtnActionPerformed
        // TODO add your handling code here:
        viewVideo("https://www.youtube.com/channel/UCbSZ77oziS0Nasdn0ffFUQQ/featured");

    }//GEN-LAST:event_agriBtnActionPerformed

    private void wondersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wondersBtnActionPerformed
        // TODO add your handling code here:
        viewVideo("https://www.youtube.com/channel/UCCkm8V9WrC9h3jRPjEUo01A");

    }//GEN-LAST:event_wondersBtnActionPerformed

    private void ecoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecoBtnActionPerformed
        // TODO add your handling code here:
        viewVideo("https://www.youtube.com/channel/UCRApdrU3BA0Pzo6MNWTD2jg");
    }//GEN-LAST:event_ecoBtnActionPerformed

    private void trimbleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trimbleBtnActionPerformed
        // TODO add your handling code here:
        viewVideo("https://www.youtube.com/user/TrimbleAgriculture");
    }//GEN-LAST:event_trimbleBtnActionPerformed

    private void ecoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecoBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecoBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agriBtn;
    private javax.swing.JButton ecoBtn;
    private javax.swing.JButton ecoBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton trimbleBtn;
    private javax.swing.JButton wondersBtn;
    // End of variables declaration//GEN-END:variables

}
