/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.Farmers.Farmer;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jagman
 */
public class LoanStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanStatusJPanel
     */
    private UserAccount account;
    public LoanStatusJPanel(UserAccount account) {
        initComponents();
        this.account = account ; 
        populateLoanTable();
    }

    
    private void populateLoanTable(){
        DefaultTableModel model = (DefaultTableModel)loanjTable.getModel();
        loanjTable.setRowSorter(new TableRowSorter(model));
        model.setRowCount(0);
        for (WorkRequest request :account.getWorkQueue().getWorkRequestList()){
            if(request instanceof BankRequest){
                
                    BankRequest req=(BankRequest)request;
                    Object[] row = new Object[11];
                    row[0] = req.getRequestDate();
                    row[1] = req.getBankName();
                    row[2] = req.getFarmerName();
                    row[3] = req.getAccountNumber();
                    row[4] = req.getLoanReason();
                    row[5] = req.getLoanAmount();
                    row[6] = req.getLoanTerm();
                    row[7] = req.getReceiver();
                    row[8] = req.getStatus();
                    row[9] = request;
                    row[10] = req.getResolveDate();
                    model.addRow(row);
                
            
            }
            
        }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanjTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Loan Status");

        loanjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request Raised Date", "Bank Name", "FarmerName", "Account Number", "Loan Reason", "Loan Amount", "Loan Term", "Receiver", "Status", "Comments", "Resolved Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(loanjTable);
        if (loanjTable.getColumnModel().getColumnCount() > 0) {
            loanjTable.getColumnModel().getColumn(0).setResizable(false);
            loanjTable.getColumnModel().getColumn(1).setResizable(false);
            loanjTable.getColumnModel().getColumn(2).setResizable(false);
            loanjTable.getColumnModel().getColumn(3).setResizable(false);
            loanjTable.getColumnModel().getColumn(5).setResizable(false);
            loanjTable.getColumnModel().getColumn(6).setResizable(false);
            loanjTable.getColumnModel().getColumn(7).setResizable(false);
            loanjTable.getColumnModel().getColumn(9).setResizable(false);
            loanjTable.getColumnModel().getColumn(10).setResizable(false);
        }

        refreshJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/clear_refresh_Other-Power-Restart-Metro-icon.png"))); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1568, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateLoanTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loanjTable;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
