/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LoanOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Validation.AlphanumericVerifier;
import Business.WorkQueue.BankRequest;
import Business.Validation.NotEmptyVerifier;
import Business.Validation.NumericVerifier;
import Business.WorkQueue.WorkRequest;
import UserInterface.InternWorkArea.InternProcessRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jagman
 */
public class LoanApplicationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanApplicationJPanel
     */
    File selectedFile ;
    private JPanel container;
    private EcoSystem system; 
    private UserAccount account;
    private WorkRequest req ;
    public LoanApplicationJPanel(JPanel panel ,EcoSystem system ,UserAccount account,WorkRequest req) {
        initComponents();
        this.container=panel;
        this.system = system;
        this.account= account; 
        this.req=req;
        applyValidationVerifier();
        
        populateBankNameCombo();
         
       
    }
    
    private void applyValidationVerifier(){
        NumericVerifier numVerify = new NumericVerifier();
        loanAmountTxtField.setInputVerifier(numVerify);
        NotEmptyVerifier emptyVerify = new NotEmptyVerifier();
        uploadFileTextField.setInputVerifier(emptyVerify);
        AlphanumericVerifier verifier = new AlphanumericVerifier();
        accountNumTxtField.setInputVerifier(verifier);
    
    }
    
    private void populateBankNameCombo(){
            bankNameComboBox.removeAllItems();
          
            if(system.getNetworkList() !=null){
	for(Network network:system.getNetworkList()){
           
		 if(null==req){
			if(network.getName().equals(account.getFarmer().getNetworkName())){
				if(network.getEnterpriseDirectory().getEnterpriseList() !=null){
					for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
						if (enterprise.getEnterpriseType().getValue().equals("Bank") ){
							bankNameComboBox.addItem(enterprise.getName());
									
						}
					
					}
				
				}else {
				
				JOptionPane.showMessageDialog(null, "Kindly create Enterprise ", "Info", JOptionPane.INFORMATION_MESSAGE);
				
				}		
			}
		 }else {
		 
		 if(network.getName().equals(req.getFarmerUserAccount().getFarmer().getNetworkName())){
			if(network.getEnterpriseDirectory().getEnterpriseList() !=null){
				for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
					if (enterprise.getEnterpriseType().getValue().equals("Bank") ){
					
					bankNameComboBox.addItem(enterprise.getName());
					
					
					}
				
				}
		
			}
		
		 }

             }

	}

 }else {
  JOptionPane.showMessageDialog(null, "Kindly create Network ", "Info", JOptionPane.INFORMATION_MESSAGE);
 
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reasonComboBox = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        bankNameComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        loanAmountTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loanTermComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        uploadFileTextField = new javax.swing.JTextField();
        attachJButton = new javax.swing.JButton();
        submitLoanReqJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        accountNumTxtField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Loan Application");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Bank Name :");

        reasonComboBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reasonComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agriculture Land", "Irrigation", "Seeds and Fertilizers" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Do you have account in this Bank ?? ");

        yesRadioButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        yesRadioButton.setText("Yes");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        noRadioButton.setText("No");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Reason for Loan:");

        bankNameComboBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bankNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bankNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Loan Amount:");

        loanAmountTxtField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanAmountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Loan Term :");

        loanTermComboBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanTermComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", " " }));
        loanTermComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Upload ITR :");

        uploadFileTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        uploadFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileTextFieldActionPerformed(evt);
            }
        });

        attachJButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        attachJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/view-profile-pic.png"))); // NOI18N
        attachJButton.setText("Attach");
        attachJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachJButtonActionPerformed(evt);
            }
        });

        submitLoanReqJButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        submitLoanReqJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/save-button.png"))); // NOI18N
        submitLoanReqJButton.setText("Sumbit Request");
        submitLoanReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLoanReqJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Account Number:");

        accountNumTxtField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        accountNumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumTxtFieldActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/arrow-back-icon.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submitLoanReqJButton))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loanAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loanTermComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(uploadFileTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accountNumTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(attachJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(bankNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(yesRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(noRadioButton))))
                        .addContainerGap(281, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankNameComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanTermComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attachJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitLoanReqJButton)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesRadioButtonActionPerformed

    private void uploadFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadFileTextFieldActionPerformed

    private void attachJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachJButtonActionPerformed
         JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.txt", "pdf");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              uploadFileTextField.setText((path));
          }
    }//GEN-LAST:event_attachJButtonActionPerformed

    private void submitLoanReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLoanReqJButtonActionPerformed
          String bankName = (String)bankNameComboBox.getSelectedItem();
          String reason = (String)reasonComboBox.getSelectedItem();
          String term = (String)loanTermComboBox.getSelectedItem();
          int loanTerm = Integer.parseInt(term);
           int loanAmount =0 ;
          try {
             loanAmount = Integer.parseInt(loanAmountTxtField.getText());
          }catch(Exception e){
          
          JOptionPane.showMessageDialog(null, "Kindly Fill loanAmount correctly !!");
          }
          String accountNum = accountNumTxtField.getText();
          DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
          Date date = new Date();
            
         if (noRadioButton.isSelected() && yesRadioButton.isSelected()){
                  
                  JOptionPane.showMessageDialog(null, "Kindly select only one radio button");
                  
         }
          else if (!(noRadioButton.isSelected() || yesRadioButton.isSelected())){
                JOptionPane.showMessageDialog(null, "Kindly select if account is opened in respective Bank or not");
                 return;
         }  
          else if (noRadioButton.isSelected()){
                 JOptionPane.showMessageDialog(null, "Kindly Open your account in respective Bank & then apply for Loan");
                 return;
          }else if( bankName == null || reason == null || term == null  ||accountNum == null || loanAmountTxtField.getText().isEmpty() ||bankName.isEmpty() || reason.isEmpty() || term.isEmpty() || accountNum.isEmpty() ){
          
           JOptionPane.showMessageDialog(null, "Kindly Fill alll the details !!");
          
          
          }else {
	         
        BankRequest request = new BankRequest();
        request.setMessage(null);
        if(req!=null ){
        
        request.setFarmerName(req.getFarmerUserAccount().getFarmer());
        }else
        {request.setFarmerName(account.getFarmer());}
        request.setStatus("Sent to the Bank");
        request.setBankName(bankName);
        request.setLoanReason(reason);
        request.setLoanTerm(loanTerm);
        request.setLoanAmount(loanAmount);
        request.setItr(selectedFile);
        request.setRequestDate(dateFormat.format(date));
        request.setAccountNumber(accountNum);
     
            Organization org = null;
            Enterprise ent = null ; 
            System.out.println("system.getNetworkList() ::" +system.getNetworkList() );
            for(Network network:system.getNetworkList()){
                
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                     System.out.println("Ban name :" +enterprise.getName());
                     System.out.println("Ban name :" +enterprise.getOrganizationDirectory().getOrganizationList().size());
                     if(enterprise.getName().equals(bankName)){
                         ent= enterprise ;
                         System.out.println("system.getNetworkList() ::" +ent );
                     
             for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LoanOrganization){
                org = organization;
                System.out.println("Loan Organization" +org);
                break;
            }
        }}}}
             if (org!=null){
               ent.getWorkQueue().getWorkRequestList().add(request);
               account.getWorkQueue().getWorkRequestList().add(request);
               JOptionPane.showMessageDialog(null, "Request Raised Successfully", "INFO", JOptionPane.INFORMATION_MESSAGE);
               }
          }
    }//GEN-LAST:event_submitLoanReqJButtonActionPerformed

    private void loanAmountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountTxtFieldActionPerformed
        
    }//GEN-LAST:event_loanAmountTxtFieldActionPerformed

    private void bankNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameComboBoxActionPerformed
       
    }//GEN-LAST:event_bankNameComboBoxActionPerformed

    private void noRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioButtonActionPerformed
       
    }//GEN-LAST:event_noRadioButtonActionPerformed

    private void accountNumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumTxtFieldActionPerformed

    private void loanTermComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTermComboBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumTxtField;
    private javax.swing.JButton attachJButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox bankNameComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField loanAmountTxtField;
    private javax.swing.JComboBox loanTermComboBox;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JComboBox<String> reasonComboBox;
    private javax.swing.JButton submitLoanReqJButton;
    private javax.swing.JTextField uploadFileTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
