/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Inventory.Inventory;
import Business.Network.Network;
import Business.Organization.FertilizerOrganization;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.SeedOrganization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FertilizerWorkRequest;
import Business.WorkQueue.SeedWorkRequest;

import Business.WorkQueue.WorkRequest;
import Business.geocoding.processing.GeocodingUtil;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Jagman
 */
public class OrderSupplies extends javax.swing.JPanel {

    
    private JPanel panel; 
    private EcoSystem system ;
    private UserAccount account ;
    private WorkRequest req ;
    /**
     * Creates new form OrderSupplies
     */
    public OrderSupplies(JPanel panel, EcoSystem system ,UserAccount account,WorkRequest req) {
        initComponents();
        this.panel = panel ;
        this.system = system ;
        this.account = account;
        this.req = req; 
        inventorPanel.setVisible(false);
        
        
    
    }
    
    public void TotalAmount(){
        
        String category=(String) categoryJCombo.getSelectedItem();
        String name=(String) nameComboBox.getSelectedItem();
        int quantity = Integer.valueOf((String)comboQuantity.getSelectedItem());
        int selectedRow = supplierTable.getSelectedRow();
        int totalAmt=0;
        ManagerOrganization manager;
        
        Enterprise ent  = (Enterprise) supplierTable.getValueAt(selectedRow, 0);{
               for (Organization org :ent.getOrganizationDirectory().getOrganizationList()) {
                   if(org instanceof ManagerOrganization){
                       manager = (ManagerOrganization) org ; 
                       for (Inventory inventory :manager.getInventoryList().getInventoryList()){
                           if(inventory.getCategory().equalsIgnoreCase(category)){
                               if(inventory.getName().equalsIgnoreCase(name)){
                                   totalAmt=totalAmt+(quantity*inventory.getPrice());
                                   System.out.println(totalAmt);
                                   txtTotalAmount.setText(String.valueOf(totalAmt));
                               }
                            }
                       }
                    }
                }
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        categoryJCombo = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        seatchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameComboBox = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btnList = new javax.swing.JButton();
        inventorPanel = new javax.swing.JPanel();
        placeOrder = new javax.swing.JButton();
        comboQuantity = new javax.swing.JComboBox();
        btnTotal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AddressjTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Place Order");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Category :");

        categoryJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seed", "Fertilizer" }));
        categoryJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryJComboActionPerformed(evt);
            }
        });

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Supplier Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        seatchButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        seatchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/view-profile-pic.png"))); // NOI18N
        seatchButton.setText("Search");
        seatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Name :");

        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Qantity :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Total Amount :");

        txtTotalAmount.setEnabled(false);
        txtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmountActionPerformed(evt);
            }
        });

        btnList.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/reports.png"))); // NOI18N
        btnList.setText("Check Price List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        inventorPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout inventorPanelLayout = new javax.swing.GroupLayout(inventorPanel);
        inventorPanel.setLayout(inventorPanelLayout);
        inventorPanelLayout.setHorizontalGroup(
            inventorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        inventorPanelLayout.setVerticalGroup(
            inventorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        placeOrder.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        placeOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/recp-cart-add.png"))); // NOI18N
        placeOrder.setText("Place Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });

        comboQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "5", "10", "20" }));
        comboQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQuantityActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/inventory.png"))); // NOI18N
        btnTotal.setText("Total amount");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel6.setText("Your Address :");

        AddressjTextArea.setColumns(20);
        AddressjTextArea.setRows(5);
        jScrollPane4.setViewportView(AddressjTextArea);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Price/Kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnList)
                            .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(seatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnList)
                                    .addComponent(jLabel2)
                                    .addComponent(categoryJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(comboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotal))
                        .addGap(58, 58, 58)
                        .addComponent(placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(inventorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAmountActionPerformed

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        String category=(String) categoryJCombo.getSelectedItem();
        String seedName=(String) nameComboBox.getSelectedItem();
        String reqQuantity=(String) comboQuantity.getSelectedItem();
        String totalAmt=txtTotalAmount.getText();
        int selectedRow = supplierTable.getSelectedRow();
        String supplierName=String.valueOf(supplierTable.getValueAt(selectedRow, 0));
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        Date date = new Date();
        
        if(totalAmt==null){
            JOptionPane.showMessageDialog(null, "Kindly select a product first");
        }
        else{
            if(category.equals("Seed")){
            
                SeedWorkRequest request = new SeedWorkRequest();
                  request.setCategory(category);
                   request.setSeedName(seedName);
                   request.setQuantity(Integer.parseInt(reqQuantity));
                   request.setTotalAmount(Integer.parseInt(totalAmt));
                   request.setSupName(supplierName);
                    request.setFarmerName(account.getFarmer());
            //request.setSender();
            request.setStatus("Sent to the Supplier");
            request.setRequestDate(dateFormat.format(date));
            request.setMessage(null);
            
            Organization org = OrganizationName(supplierName,category);
            RaiseRequest(org,request);
            
            }else {
            
            FertilizerWorkRequest request = new FertilizerWorkRequest();
                  request.setCategory(category);
                   request.setFertName(seedName);
                   request.setQuantity(Integer.parseInt(reqQuantity));
            request.setTotalAmount(Integer.parseInt(totalAmt));
            request.setSupName(supplierName);
            request.setFarmerName(account.getFarmer());
            //request.setSender();
            request.setStatus("Sent to the Supplier");
            request.setRequestDate(dateFormat.format(date));
            request.setMessage(null);
            
             Organization org = OrganizationName(supplierName,category);
            RaiseRequest(org,request);
            
            
            }
     
        }
        
   
    }//GEN-LAST:event_placeOrderActionPerformed
    
    
    private void RaiseRequest(Organization org , WorkRequest request){
    
                if (org!=null){
               org.getWorkQueue().getWorkRequestList().add(request);
               account.getWorkQueue().getWorkRequestList().add(request);
               JOptionPane.showMessageDialog(null, "Request Raised Successfully", "INFO", JOptionPane.INFORMATION_MESSAGE);
               
               
               nameComboBox.removeAllItems();
               txtTotalAmount.setText("");
               }
    
    
    
    }
    
    private Organization OrganizationName(String supplierName,String category){
    
            Organization org = null;
            Enterprise ent = null ; 
            for(Network network:system.getNetworkList()){
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                     System.out.println("Ban name :" +enterprise.getName());
                     System.out.println("Ban name :" +enterprise.getOrganizationDirectory().getOrganizationList().size());
                     if(enterprise.getName().equals(supplierName)){
                         ent= enterprise ;
                         System.out.println("system.getNetworkList() ::" +ent );
                     
             for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                if(category.equals("Seed")){
                    if (organization instanceof SeedOrganization){
                        org = organization;
                        System.out.println("SeedOrganization" +org);
                        break;
                    }
                }
                else{
                    if (organization instanceof FertilizerOrganization){
                        org = organization;
                        System.out.println("Fertilizer Organization" +org);
                        break;
                    }
                }
            
        }}}}
    
    
    return org ;
   
    }
    private void seatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatchButtonActionPerformed
        String address = AddressjTextArea.getText();
        account.getFarmer().setAddress(address);
        
        DefaultTableModel model = (DefaultTableModel)supplierTable.getModel();
        supplierTable.setRowSorter(new TableRowSorter(model));
        System.out.println("Network name : " +account.getFarmer().getNetworkName()) ;
        model.setRowCount(0);
       List<Enterprise> allEnteprises = new ArrayList<Enterprise>();
        for (Network network : system.getNetworkList()) {
            System.out.println(network.getName());
            if(network.getName().equalsIgnoreCase(account.getFarmer().getNetworkName())){
            List<Enterprise> enterprises = network.getEnterpriseDirectory().getEnterpriseList();
            allEnteprises.addAll(enterprises);

        }}
        System.out.println("Enterprise List" +allEnteprises);

        /**
         * Get farmer obj here.
         */
        allEnteprises = GeocodingUtil.getNearestEnteprisesForFarmer(allEnteprises, account.getFarmer());
        System.out.println(allEnteprises);
       for (Enterprise enterprise : allEnteprises){
                {
                    if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Supplier") ){
                         Object[] row = new Object[2];
                         row[0] = enterprise;
                         row[1] = enterprise.getAddress();
                         model.addRow(row);
                         
                        
                    }
                }
                
       }      
                    
                    
        
        
        
        
        
    }//GEN-LAST:event_seatchButtonActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        inventorPanel.setVisible(true);
        int selectedRow = supplierTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        ManagerOrganization manager ; 
        model.setRowCount(0);
        String category=(String) categoryJCombo.getSelectedItem();
         

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table");
        } else {

            Enterprise ent  = (Enterprise) supplierTable.getValueAt(selectedRow, 0);
               for (Organization org :ent.getOrganizationDirectory().getOrganizationList()) {
                   if(org instanceof ManagerOrganization){
                       manager = (ManagerOrganization) org ; 
                       for (Inventory inventory :manager.getInventoryList().getInventoryList()){
                           if(inventory.getCategory().equalsIgnoreCase(category)){
                                Object[] row = new Object[2];
                                row[0] = inventory.getName();
                                row[1]=inventory.getPrice();
                                model.addRow(row);
                                
                                nameComboBox.addItem(inventory.getName());
                            }
                       }
                   }
        
                    
        }
                
            }
    }//GEN-LAST:event_btnListActionPerformed

    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameComboBoxActionPerformed

    private void comboQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuantityActionPerformed
        // TODO add your handling code here:
        
       
       
    }//GEN-LAST:event_comboQuantityActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        TotalAmount();
    }//GEN-LAST:event_btnTotalActionPerformed

    private void categoryJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryJComboActionPerformed

    }//GEN-LAST:event_categoryJComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressjTextArea;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> categoryJCombo;
    private javax.swing.JComboBox comboQuantity;
    private javax.swing.JPanel inventorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> nameComboBox;
    private javax.swing.JButton placeOrder;
    private javax.swing.JButton seatchButton;
    private javax.swing.JTable supplierTable;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
