/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LoanApproval;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankRequest;
import Business.WorkQueue.WorkRequest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nidhi
 */
public class LoanApprovalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanApprovalWorkAreaJPanel
     */
    private JPanel container;    
    private UserAccount account; 
    private Enterprise enterprise;
    private BankRequest req;
    private WorkRequest request;
    
    public LoanApprovalWorkAreaJPanel(JPanel container, Enterprise enterprise ,UserAccount account)
 {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.account = account;
        this.req=req;
        this.request=request;
        populateTable();
        DetailsPanel.setVisible(false);
        
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) loanApprovalWorkJTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            BankRequest req =(BankRequest)request;
            Object[] row = new Object[6];
            row[0] = req.getRequestDate();
            row[1] = req.getFarmerName();  
            row[2] = req.getStatus();
            row[3] = request;
            row[4] = request.getReceiver();
            row[5] = req.getResolveDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanApprovalWorkJTable = new javax.swing.JTable();
        disapproveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showDetails = new javax.swing.JButton();
        DetailsPanel = new javax.swing.JPanel();
        acctNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loanAmont = new javax.swing.JTextField();
        loanReason = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hideButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        assignBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        assignBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/assigntome.png"))); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        approveBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        approveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/save-button.png"))); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        loanApprovalWorkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Req raised date", "Farmer Name", "Status", "Comments", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(loanApprovalWorkJTable);
        if (loanApprovalWorkJTable.getColumnModel().getColumnCount() > 0) {
            loanApprovalWorkJTable.getColumnModel().getColumn(0).setResizable(false);
            loanApprovalWorkJTable.getColumnModel().getColumn(1).setResizable(false);
            loanApprovalWorkJTable.getColumnModel().getColumn(2).setResizable(false);
            loanApprovalWorkJTable.getColumnModel().getColumn(3).setResizable(false);
            loanApprovalWorkJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        disapproveBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        disapproveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/cancel.png"))); // NOI18N
        disapproveBtn.setText("Disapprove");
        disapproveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapproveBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Loan Approval Work Area");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/submit.png"))); // NOI18N
        jButton1.setText("Send Email");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showDetails.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        showDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-drug-to-prescription.png"))); // NOI18N
        showDetails.setText("Show Details ");
        showDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsActionPerformed(evt);
            }
        });

        DetailsPanel.setBackground(new java.awt.Color(153, 153, 255));
        DetailsPanel.setEnabled(false);

        acctNum.setEditable(false);
        acctNum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        acctNum.setEnabled(false);
        acctNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Account Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Loan Amount :");

        loanAmont.setEditable(false);
        loanAmont.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanAmont.setEnabled(false);
        loanAmont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmontActionPerformed(evt);
            }
        });

        loanReason.setEditable(false);
        loanReason.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanReason.setEnabled(false);
        loanReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanReasonActionPerformed(evt);
            }
        });

        loanTermTextField.setEditable(false);
        loanTermTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        loanTermTextField.setEnabled(false);
        loanTermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Loan Term:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Loan Reason :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Details ");

        hideButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        hideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/add-another-durg.png"))); // NOI18N
        hideButton.setText("Hide");
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 103, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loanAmont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(417, 417, 417)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(showDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(approveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disapproveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assignBtn)
                            .addComponent(showDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(disapproveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow =loanApprovalWorkJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } 
        else {
            WorkRequest request = (WorkRequest) loanApprovalWorkJTable.getValueAt(selectedRow, 3);
            if (request.getReceiver() != null) {
                JOptionPane.showMessageDialog(null, "This request is already assigned");
            }else if (request.getStatus().equalsIgnoreCase("Disapproved")) {
            JOptionPane.showMessageDialog(null,"The request has been already disapproved ", "warning", JOptionPane.WARNING_MESSAGE);
            }else if (request.getStatus().equalsIgnoreCase("Intermidate") ||request.getStatus().equalsIgnoreCase("Sent to the Bank") || request.getStatus().equalsIgnoreCase("Pending with Bank Loan Dept")||request.getStatus().equalsIgnoreCase("Verified") || request.getStatus().equalsIgnoreCase("Rejected")) {
            
             JOptionPane.showMessageDialog(null,"The request is assigned to some other Department", "warning", JOptionPane.WARNING_MESSAGE);
            }
            
            else { 
                request.setReceiver(account);
                populateTable();
               
        }}
    }//GEN-LAST:event_assignBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
          Date date = new Date();
        int selectedRow = loanApprovalWorkJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request from the table","Info", JOptionPane.INFORMATION_MESSAGE);
        }else {
         WorkRequest request = (WorkRequest) loanApprovalWorkJTable.getValueAt(selectedRow, 3);
         
         if(request.getStatus().equals("Approved")) {
           JOptionPane.showMessageDialog(null, "This request is already approved", "Info", JOptionPane.INFORMATION_MESSAGE);  
         }else if (request.getStatus().equalsIgnoreCase("Disapproved")) {
             
            JOptionPane.showMessageDialog(null,"The request has been already disapproved ", "warning", JOptionPane.WARNING_MESSAGE);
         }else if (request.getReceiver() != null && request.getReceiver() != account) {
        
        JOptionPane.showMessageDialog(null,"The request is not assigned to you !!", "warning", JOptionPane.WARNING_MESSAGE);
        }else if (request.getReceiver() == null){ 
         JOptionPane.showMessageDialog(null,"Assign the request first !!", "warning", JOptionPane.WARNING_MESSAGE);
        
        }else {
             
                request.setStatus("Approved");
                request.setResolveDate(dateFormat.format(date));
                
                populateTable();
                
        }}
    }//GEN-LAST:event_approveBtnActionPerformed

    private void disapproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapproveBtnActionPerformed
        // TODO add your handling code here:
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
          Date date = new Date();
        int selectedRow = loanApprovalWorkJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request from the table","Info", JOptionPane.INFORMATION_MESSAGE);
        }else {
        
        WorkRequest request = (WorkRequest) loanApprovalWorkJTable.getValueAt(selectedRow, 3);
        if(request.getStatus().equals("Disapproved")) {
           JOptionPane.showMessageDialog(null, "This request is  already disapproved","Info", JOptionPane.INFORMATION_MESSAGE);  
         }else if (request.getReceiver() != null && request.getReceiver() != account) {
        
        JOptionPane.showMessageDialog(null,"The request is not assigned to you !!", "warning", JOptionPane.WARNING_MESSAGE);
        }else if (request.getReceiver() == null){ 
         JOptionPane.showMessageDialog(null,"Assign the request first !!", "warning", JOptionPane.WARNING_MESSAGE);
        
        }else {
            String result = (String)JOptionPane.showInputDialog(null, "Enter Reason of Disapproval:");
                request.setStatus("Disapproved"); 
                request.setMessage(result);
                request.setResolveDate(dateFormat.format(date));
                populateTable();
                
        }
        }
    }//GEN-LAST:event_disapproveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = loanApprovalWorkJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request from the table","Info", JOptionPane.INFORMATION_MESSAGE);
        }else {
        WorkRequest request = (WorkRequest) loanApprovalWorkJTable.getValueAt(selectedRow, 3);
       if(request.getStatus().equalsIgnoreCase("Approved") ||request.getStatus().equalsIgnoreCase("Disapproved") ) 
       {
        String to = request.getFarmerName().getEmail();
        String from = "jagmangrewal9@gmail.com";
        String host = "smtp.gmail.com";
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        Session session = Session.getInstance(properties,
                new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication("jagmangrewal9@gmail.com", "Waheguru!13");
            }
        }
        );
        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject("Loan Status");
            message.setText("Hello, Your Loan as been " + request.getStatus() + ". Kindly connect with Bank for more details");
                    
            javax.mail.Transport.send(message);
            JOptionPane.showMessageDialog(null, "message sent to " );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }else {
           
           JOptionPane.showMessageDialog(null, "Kindly approve/disapprove the request first !!","Info", JOptionPane.INFORMATION_MESSAGE);
       }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsActionPerformed
        int selectedRow = loanApprovalWorkJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request from the table");
        } else {

            WorkRequest request = (WorkRequest) loanApprovalWorkJTable.getValueAt(selectedRow, 3);
            BankRequest req=(BankRequest)request;
            DetailsPanel.setVisible(true);
            loanAmont.setText(Integer.toString(req.getLoanAmount()));
            acctNum.setText(req.getAccountNumber());
            loanReason.setText(req.getLoanReason());
            loanTermTextField.setText(Integer.toString(req.getLoanTerm()));

        }
    }//GEN-LAST:event_showDetailsActionPerformed

    private void acctNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumActionPerformed

    private void loanAmontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmontActionPerformed

    private void loanReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanReasonActionPerformed

    private void loanTermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTermTextFieldActionPerformed

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        DetailsPanel.setVisible(false);
    }//GEN-LAST:event_hideButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JTextField acctNum;
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton disapproveBtn;
    private javax.swing.JButton hideButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanAmont;
    private javax.swing.JTable loanApprovalWorkJTable;
    private javax.swing.JTextField loanReason;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JButton showDetails;
    // End of variables declaration//GEN-END:variables
}
